NeoTech-Software/Android-Root-Coverage-Plugin

- .travis.yml
- gradle/dependencies.gradle
- gradlew.bat
- plugin/build.gradle
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
Not perfect, but better than nothing.
> Add configuration for building on Travis CI

- README.md
- gradle.properties
- The minimum supported Gradle version is now 4.10.1, which makes it equal to the minimum supported version that is supported by the Android Gradle plugin version 3.3.0.
> Release 1.1.1

- README.md
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/app/src/androidTest/java/org/neotech/app/multimoduleapplication/TouchLibraryCodeTest.kt
- plugin/src/test/test-fixtures/multi-module/library_android/build.gradle
- Update Gradle to version 5.4.1
- Update Kotlin to version 1.3.40
- Update Android Gradle Plugin to version 3.4.1
- Update AndroidX AppCompat to version 1.0.2
- Update Google Truth to version 0.45
- Update AndroidX Test Runner to version 1.1.1
- Update Espresso Core to version 3.1.1
- Update Apache Commons CSV to version 1.7
- Update target and compile SDK versions to API level 29 (Android Q)
- Use `androidx.test.ext.junit.runners.AndroidJUnit4` instead of `androidx.test.runner.AndroidJUnit4`
- Added Gradle version 5.4.1 to test fixture
> Feature/android gradle plugin 3.4

- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- Update Gradle to version 5.5.1
- Update Kotlin to version 1.3.41
- Update Google Truth to version 1.0 🎉
> Update Gradle, Kotlin and Google Truth dependencies

- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- Update Kotlin to version 1.3.60
- Update Android Gradle Plugin to version 3.5.2
- Update AndroidX AppCompat to version 1.1.0
- Update AndroidX Test Runner to version 1.2.0
- Update AndroidX Espresso to version 3.2.0
- Update AndroidX JUnit Extensions to version 1.1.1
- Update Gradle to version 5.6.4
This update makes the minimum supported Gradle version 5.4.1 and maximum supported Gradle version 5.6.4 (same Gradle versions as supported by Android Gradle Plugin version 3.5.2)
> Update Kotlin, Gradle, Android Gradle Plugin and AndroidX dependencies

- README.md
- build.gradle
- gradle.properties
- gradle/dependencies.gradle
Release highlights:
- Official support for Android Gradle Plugin 3.5 and Gradle 5.6.
- New configuration options that replace the now deprecated `skipTestExecution` and `testTypes` options:
- `executeTests`: When false the plugin does not execute any tests, so you can run them manually or remote (Firebase Test Lab)
- `executeAndroidTests`: Same as executeTests except that this only affects the instrumented Android tests
- `executeUnitTests`: Same as executeTests except that this only affects the unit tests
- `includeAndroidTestResults`: When true include results from instrumented Android tests into the coverage report
- `includeUnitTestResults `: When true include results from unit tests into the coverage report
> Release 1.2.0

- README.md
- gradle.properties
This release officially supports Android Gradle Plugin version 3.6.x and therefore raises the minimum Gradle version to 5.6.4. No other changes are included in this release.
> Release 1.3.0

- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/CsvCoverageReport.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
> Add coverage tasks for reports on module level

- README.md
- gradle/dependencies.gradle
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePluginExtension.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePluginExtensionTest.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/app/src/main/AndroidManifest.xml
- plugin/src/test/test-fixtures/multi-module/app/src/main/java/org/neotech/app/RobolectricTestedActivity.java
- plugin/src/test/test-fixtures/multi-module/app/src/main/res/layout/activity_robolectric_tested.xml
- plugin/src/test/test-fixtures/multi-module/app/src/test/java/org/neotech/app/RobolectricUnitTest.java
- plugin/src/test/test-fixtures/multi-module/build.gradle
This adds an option `includeNoLocationClasses` to the rootCoverage extension to set Jacoco's `includeNoLocationClasses`. Which makes it easier to support the Jacoco + Robolectric use-case.
> Improve support for Robolectric

- README.md
- plugin/gradle.properties
Release highlights:
- Support for Android Gradle Plugin 4.1 _(although version 1.3.0 also works fine with AGP 4.1)_;
- Support for per module code coverage. Generate a module specific report by running `./gradlew yourModule:codeCoverage`;
- New configuration option `includeNoLocationClasses` which (like the name implies) sets Jacoco's `includeNoLocationClasses`. This makes using the plugin in combination with Robolectric easier, since Robolectric often requires `includeNoLocationClasses` to be set to `true`;
- The "Jacoco has been automatically applied" message is not longer a warning but now an info message.
> Release 1.4.0

- .github/workflows/build.yml
- gradle/dependencies.gradle
- gradle/plugin-version-handler.gradle
- gradle/wrapper/gradle-wrapper.properties
- plugin/build.gradle
- plugin/gradle.properties
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/CsvCoverageReport.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/library_android/build.gradle
In Android Gradle Plugin 7.0 a bug was introduced causing instrumented coverage for Android library projects to fail: https://issuetracker.google.com/issues/195860510
This bug has finally been fixed in an alpha release of AGP 7.2 (`7.2.0-alpha06`). Unfortunately no hot-fix has been released for 7.0 or the 7.1 (which is in beta), only the canary version (7.2) received this fix for now.
As long as there are no hot-fixes for AGP 7.0 and 7.1 specifically I will work towards a release that works at least with AGP 7.2.
This PR contains the necessary changes to work with AGP version 7.2.0-alpha06 and also includes the following other changes:
- Increased the target and compile SDK version to API level 31 for the test fixtures. This also requires the build to use Java 11.
- Upgraded several test …
> Support for Android Gradle Plugin version 7

- plugin/build.gradle
This fixes:
- The usage of sourceCompatibility and targetCompatibility
- The command reference to upload new artifacts to Maven Central
> Correct usage of sourceCompatibility and targetCompatibility

- gradle/libs.versions.toml
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
Updated the Android Gradle Plugin dependency to stable 7.2.0, also updated the integration test to also run on the latest Gradle release candidate (7.5-rc-1).
> Update: Android Gradle Plugin dependency to stable 7.2.0

- README.md
- plugin/gradle.properties
_Google finally released a stable version of the Android Gradle Plugin 7.2 that fixes #36, a bug introduced in Android Gradle Plugin 7.0!_
- Based on Android Gradle Plugin 7.2 API
- Compatible with Gradle version 7.3+
**Notable changes since 1.4.0:**
- Most of the plugin has been rewritten to only make use of public Android Gradle Plugin API's, functionally this should not change anything compared to previous releases.
- Adds a minimum required Android Gradle Plugin version check, using an Android Gradle Plugin version that is too old will result in a Gradle build error.
- No longer logs warning messages for (sub)projects (modules) that do not use the Android Gradle Plugin. Instead this is now an info message. This info message will only show for (sub)projects that have a build.gradle …
> Release 1.5.0

- plugin/build.gradle
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/app/src/main/java/org/neotech/app/AppJava.java
- plugin/src/test/test-fixtures/multi-module/library_android/build.gradle
- plugin/src/test/test-fixtures/multi-module/library_android/src/main/java/org/neotech/library/android/LibraryAndroidJava.java
Apparently using `variant.sources.java.all` in AGP 7.2 causes `BuildConfig` files to disappear or not generate at all, this is very likely a bug in AGP 7.2 because it is working in AGP 7.3.0-beta01. For now this is a workaround that reintroduces code that utilizes old non-public AGP code, but at least this code is working.
Fixes #54
> Fix: BuildConfig file not generated/disappearing

- README.md
- plugin/gradle.properties
Fixes #54 but reintroduces the dependency on the full Android Gradle Plugin instead of just depending on the Android Gradle Plugin API. This should be temporary as this workaround does not seem to be needed in AGP 7.3.0.
> Release 1.5.1

- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
Changed `Project.getRelativePath()` to `Project.getRelativeProjectPath()`, since what was needed is the logical Gradle (project) relative path, not the file-system relative path.
Fixes #64
> Fix: Crash during configuration on Windows

- gradle/libs.versions.toml
- plugin/build.gradle
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/JaCoCoConfiguration.kt
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/utilities/AndroidGradlePluginExtensions.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/app/src/main/AndroidManifest.xml
- plugin/src/test/test-fixtures/multi-module/library_android/build.gradle
- plugin/src/test/test-fixtures/multi-module/library_android/src/main/AndroidManifest.xml
This changes the plugin to specifically support Android Gradle Plugin 7.3.
This mainly means that the plugin now also checks `enableUnitTestCoverage` and `enableAndroidTestCoverage` as well as the now (in AGP 7.3) deprecated property `testCoverageEnabled`.
> Update: support for Android Gradle Plugin 7.3

- README.md
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePluginExtension.kt
To follow the convention of the Android Gradle Plugin, it makes sense to only support the specific `executeAndroidTests` and `executeUnitTests` properties (just like AGP 7.3 now has `enableUnitTestCoverage` and `enableAndroidTestCoverage`).
> Change: Deprecate executeTests configuration property

- .github/workflows/build.yml
- .gitignore
- README.md
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/JaCoCoConfiguration.kt
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePluginExtension.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/util/ProjectGeneration.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/util/SimpleTemplate.kt
- plugin/src/test/test-fixtures/multi-module/app/build.gradle
- plugin/src/test/test-fixtures/multi-module/build.gradle.tmp
- plugin/src/test/test-fixtures/multi-module/configurations/connected-device.properties
- plugin/src/test/test-fixtures/multi-module/configurations/gradle-managed-device.properties
- plugin/src/test/test-fixtures/multi-module/library_android/build.gradle
This PR adds experimental support for running instrumented tests on Gradle Managed Devices.
Some credit has to go to @bddckr for his initial PR on this (see: #73)
> Add: Support for running instrumented tests on Gradle Managed Devices

- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePlugin.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/IntegrationTest.kt
- plugin/src/test/kotlin/org/neotech/plugin/rootcoverage/util/GradleBuildExtensions.kt
- plugin/src/test/test-fixtures/multi-module/configurations/gradle-managed-device-dont-execute-android-tests.yaml
In our project we are using gradle managed devices to execute ui tests. Ui tests launch configuration is a bit complicated in our use case, so I had to launch ui tests separately from `Android-Root-Coverage-Plugin`. And then after ui tests have finished it's execution, I am using `:rootCoverageReport"` The problem here, is that coverage results from ui tests are being ignored by `:rootCoverageReport`. This happens only with gradle managed devices, if I manually execute ui tests on connected emulator, and than use `:rootCoverageReport` to create aggregated coverage report, everything works as expected.
I have created new configuration `gradle-managed-device-dont-execute-android-tests.yaml` for `IntegrationTest.kt`, that reproduces the issue above.
This pull request also contains fix of …
> Fix: rootCoverageReport ignores androidTests coverage results when executeAndroidTests is false

- README.md
- plugin/gradle.properties
- Fixed: Code coverage data not picked up when using Gradle Managed Devices in combination with flavors (#102)
- Fixed: Code coverage data not picked up when using Gradle Managed Devices in combination with executeAndroidTests=false (thanks to @k4k7us23)  (#104)
- Based on Android Gradle Plugin 8.6 API
- Compatible with Gradle version 8.7+
> Release 1.9.0

- plugin/src/main/kotlin/org/neotech/plugin/rootcoverage/RootCoveragePluginExtension.kt
This is especially helpful when using Kotlin (.kts) as language for build files.
Closes: #112
> Add: Extension function on 'Project' to easily configure the 'rootCoverage' extension

- README.md
- plugin/gradle.properties
- New: Extension function for the rootCoverage block when using .kts build files (#112)
- Based on Android Gradle Plugin 8.8 API
- Compatible with Gradle version 8.10.2+
> Release 1.10.0
